version: '3'
services:
  redis:
    image: 'redis:latest'
    ports:
      - "6379"
  nginx:
    depends_on:
      - api
      - fe
    restart: always
    image:
      shmeeshmee/rep-task:latest
    ports:
      - '3050:80'
  api:
    image:
      shmeeshmee/rep-task-be:latest
    environment:
      - PORT=8082
      - REDIS_PORT=6379
      - REDIS_DRIVER=redis
    ports:
      - "8082:8082"
  fe:
    stdin_open: true
    image:
      shmeeshmee/rep-task-fe:latest
    environment:
      - API_PORT=8082
      - API_HOST=api
    ports:
      - "3000:3000"