version: '3'
services:
  redis:
    image: 'redis:latest'
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /api:/app
    environment:
      - PORT=8082
      - DB_DRIVER_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=store
      - DEBUG_LEVEL=Debug
    # ports:
    #   - 8082:8082
  fe:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    # ports:
    #   - 3000:3000
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
  nginx:
    depends_on:
      - api
      - fe
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'