version: '3'
services:
  redis:
    image: 'redis:latest'
  # postgres:
  #   image: 'postgres:latest'
  #   environment:
  #     - POSTGRES_DB=pack
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /api:/app
    environment:
      - PORT=8082
      - DB_DRIVER_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=store
      - DEBUG_LEVEL=Debug
    ports:
      - 8082:8082
  # migrate:
  #   build:
  #     context: ./migrations
  #     dockerfile: Dockerfile.dev
  #   restart: on-failure
  #   depends_on:
  #     - postgres
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_USER=postgres
  #     - DB_PASSWORD=password
  #     - DB_NAME=pack
  #     - DB_SSL=disable
  #   volumes:
  #     - ./migrations:/usr/app/migrations