FROM golang:alpine
WORKDIR /usr/app

RUN go install github.com/pressly/goose/v3/cmd/goose@latest
COPY *.sql /migrations/

ENV DB_USER=DB_USER
ENV DB_PASSWORD=DB_PASSWORD
ENV DB_NAME=DB_NAME
ENV DB_HOST=DB_HOST

CMD goose -dir migrations postgres "host=${DB_HOST} user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME} sslmode=disable" up